include_configs:
  - ../common/train.yaml
  - data_pairwise.yaml

name: 'cape_self/basis'
model: 'basis_net_self'

batch_size: 2

# Quantization size of sparse convolution network
voxel_size: 0.01

# Path to the trained descriptor network
desc_checkpoint: "out/cape_self/desc/best.pth"

# Number of basis functions
n_basis: 24

# Basis network configuration
backbone_args:
  channels: [-1, 32, 64, 128, 256]
  tr_channels: [-1, 64, 64, 64, 128]

# Refinement network configuration
refine_args:
  channels: [-1, 32, 64]
  tr_channels: [-1, 64, 64]

# Consistency loss (Equ.11) weight
ctc_weight: 0.05
flow_f_weight: 0.1        # Regularize F^f

# Type of robust kernel. Only huber is supported.
robust_kernel:
  type: "huber"
  robust_k: 0.05
  robust_iter: 2

# t parameter in Equ.(5)
t_init: 0.1
t_min: 0.01

# Self-supervised loss
self_supervised_loss:
  chamfer_weight: 1.0
  laplacian_weight: 5.0
  smooth_weight: 1.0
